# Generated by Django 4.2 on 2023-05-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_avatar_delete_perro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('subtitulo', models.CharField(max_length=30)),
                ('Contenido', models.CharField(max_length=500)),
                ('autor', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Veterinario',
        ),
    ]
